@startuml

title __MODELS's Class Diagram__\n

  namespace com.orange {
    namespace models {
      class com.orange.models.Astro {
          - additionalProperties : Map<String, Object>
          - moonIllumination : String
          - moonPhase : String
          - moonrise : String
          - moonset : String
          - sunrise : String
          - sunset : String
          + Astro()
          + Astro()
          + getAdditionalProperties()
          + getMoonIllumination()
          + getMoonPhase()
          + getMoonrise()
          + getMoonset()
          + getSunrise()
          + getSunset()
          + setAdditionalProperty()
          + setMoonIllumination()
          + setMoonPhase()
          + setMoonrise()
          + setMoonset()
          + setSunrise()
          + setSunset()
          + toString()
          + withAdditionalProperty()
          + withMoonIllumination()
          + withMoonPhase()
          + withMoonrise()
          + withMoonset()
          + withSunrise()
          + withSunset()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Condition {
          - additionalProperties : Map<String, Object>
          - code : int
          - icon : String
          - text : String
          + Condition()
          + Condition()
          + getAdditionalProperties()
          + getCode()
          + getIcon()
          + getText()
          + setAdditionalProperty()
          + setCode()
          + setIcon()
          + setText()
          + toString()
          + withAdditionalProperty()
          + withCode()
          + withIcon()
          + withText()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Condition_ {
          - additionalProperties : Map<String, Object>
          - code : int
          - icon : String
          - text : String
          + Condition_()
          + Condition_()
          + getAdditionalProperties()
          + getCode()
          + getIcon()
          + getText()
          + setAdditionalProperty()
          + setCode()
          + setIcon()
          + setText()
          + toString()
          + withAdditionalProperty()
          + withCode()
          + withIcon()
          + withText()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Condition__ {
          - additionalProperties : Map<String, Object>
          - code : int
          - icon : String
          - text : String
          + Condition__()
          + Condition__()
          + getAdditionalProperties()
          + getCode()
          + getIcon()
          + getText()
          + setAdditionalProperty()
          + setCode()
          + setIcon()
          + setText()
          + toString()
          + withAdditionalProperty()
          + withCode()
          + withIcon()
          + withText()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Current {
          - additionalProperties : Map<String, Object>
          - cloud : int
          - feelslikeC : double
          - feelslikeF : double
          - gustKph : double
          - gustMph : double
          - humidity : int
          - isDay : int
          - lastUpdated : String
          - lastUpdatedEpoch : int
          - precipIn : int
          - precipMm : int
          - pressureIn : double
          - pressureMb : int
          - tempC : double
          - tempF : int
          - uv : int
          - visKm : double
          - visMiles : int
          - windDegree : int
          - windDir : String
          - windKph : double
          - windMph : double
          + Current()
          + Current()
          + getAdditionalProperties()
          + getCloud()
          + getCondition()
          + getFeelslikeC()
          + getFeelslikeF()
          + getGustKph()
          + getGustMph()
          + getHumidity()
          + getIsDay()
          + getLastUpdated()
          + getLastUpdatedEpoch()
          + getPrecipIn()
          + getPrecipMm()
          + getPressureIn()
          + getPressureMb()
          + getTempC()
          + getTempF()
          + getUv()
          + getVisKm()
          + getVisMiles()
          + getWindDegree()
          + getWindDir()
          + getWindKph()
          + getWindMph()
          + setAdditionalProperty()
          + setCloud()
          + setCondition()
          + setFeelslikeC()
          + setFeelslikeF()
          + setGustKph()
          + setGustMph()
          + setHumidity()
          + setIsDay()
          + setLastUpdated()
          + setLastUpdatedEpoch()
          + setPrecipIn()
          + setPrecipMm()
          + setPressureIn()
          + setPressureMb()
          + setTempC()
          + setTempF()
          + setUv()
          + setVisKm()
          + setVisMiles()
          + setWindDegree()
          + setWindDir()
          + setWindKph()
          + setWindMph()
          + toString()
          + withAdditionalProperty()
          + withCloud()
          + withCondition()
          + withFeelslikeC()
          + withFeelslikeF()
          + withGustKph()
          + withGustMph()
          + withHumidity()
          + withIsDay()
          + withLastUpdated()
          + withLastUpdatedEpoch()
          + withPrecipIn()
          + withPrecipMm()
          + withPressureIn()
          + withPressureMb()
          + withTempC()
          + withTempF()
          + withUv()
          + withVisKm()
          + withVisMiles()
          + withWindDegree()
          + withWindDir()
          + withWindKph()
          + withWindMph()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Day {
          - additionalProperties : Map<String, Object>
          - avghumidity : int
          - avgtempC : double
          - avgtempF : double
          - avgvisKm : double
          - avgvisMiles : int
          - dailyChanceOfRain : String
          - dailyChanceOfSnow : String
          - dailyWillItRain : int
          - dailyWillItSnow : int
          - maxtempC : double
          - maxtempF : double
          - maxwindKph : double
          - maxwindMph : double
          - mintempC : double
          - mintempF : double
          - totalprecipIn : double
          - totalprecipMm : double
          - uv : int
          + Day()
          + Day()
          + getAdditionalProperties()
          + getAvghumidity()
          + getAvgtempC()
          + getAvgtempF()
          + getAvgvisKm()
          + getAvgvisMiles()
          + getCondition()
          + getDailyChanceOfRain()
          + getDailyChanceOfSnow()
          + getDailyWillItRain()
          + getDailyWillItSnow()
          + getMaxtempC()
          + getMaxtempF()
          + getMaxwindKph()
          + getMaxwindMph()
          + getMintempC()
          + getMintempF()
          + getTotalprecipIn()
          + getTotalprecipMm()
          + getUv()
          + setAdditionalProperty()
          + setAvghumidity()
          + setAvgtempC()
          + setAvgtempF()
          + setAvgvisKm()
          + setAvgvisMiles()
          + setCondition()
          + setDailyChanceOfRain()
          + setDailyChanceOfSnow()
          + setDailyWillItRain()
          + setDailyWillItSnow()
          + setMaxtempC()
          + setMaxtempF()
          + setMaxwindKph()
          + setMaxwindMph()
          + setMintempC()
          + setMintempF()
          + setTotalprecipIn()
          + setTotalprecipMm()
          + setUv()
          + toString()
          + withAdditionalProperty()
          + withAvghumidity()
          + withAvgtempC()
          + withAvgtempF()
          + withAvgvisKm()
          + withAvgvisMiles()
          + withCondition()
          + withDailyChanceOfRain()
          + withDailyChanceOfSnow()
          + withDailyWillItRain()
          + withDailyWillItSnow()
          + withMaxtempC()
          + withMaxtempF()
          + withMaxwindKph()
          + withMaxwindMph()
          + withMintempC()
          + withMintempF()
          + withTotalprecipIn()
          + withTotalprecipMm()
          + withUv()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Forecast {
          - additionalProperties : Map<String, Object>
          - forecastday : List<Forecastday>
          + Forecast()
          + Forecast()
          + getAdditionalProperties()
          + getForecastday()
          + setAdditionalProperty()
          + setForecastday()
          + toString()
          + withAdditionalProperty()
          + withForecastday()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Forecastday {
          - additionalProperties : Map<String, Object>
          - date : String
          - dateEpoch : int
          - hour : List<Hour>
          + Forecastday()
          + Forecastday()
          + getAdditionalProperties()
          + getAstro()
          + getDate()
          + getDateEpoch()
          + getDay()
          + getHour()
          + setAdditionalProperty()
          + setAstro()
          + setDate()
          + setDateEpoch()
          + setDay()
          + setHour()
          + toString()
          + withAdditionalProperty()
          + withAstro()
          + withDate()
          + withDateEpoch()
          + withDay()
          + withHour()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Hour {
          - additionalProperties : Map<String, Object>
          - chanceOfRain : String
          - chanceOfSnow : String
          - cloud : int
          - dewpointC : double
          - dewpointF : double
          - feelslikeC : double
          - feelslikeF : double
          - gustKph : double
          - gustMph : double
          - heatindexC : double
          - heatindexF : double
          - humidity : int
          - isDay : int
          - precipIn : double
          - precipMm : double
          - pressureIn : double
          - pressureMb : int
          - tempC : double
          - tempF : double
          - time : String
          - timeEpoch : int
          - uv : int
          - visKm : int
          - visMiles : int
          - willItRain : int
          - willItSnow : int
          - windDegree : int
          - windDir : String
          - windKph : double
          - windMph : double
          - windchillC : double
          - windchillF : double
          + Hour()
          + Hour()
          + getAdditionalProperties()
          + getChanceOfRain()
          + getChanceOfSnow()
          + getCloud()
          + getCondition()
          + getDewpointC()
          + getDewpointF()
          + getFeelslikeC()
          + getFeelslikeF()
          + getGustKph()
          + getGustMph()
          + getHeatindexC()
          + getHeatindexF()
          + getHumidity()
          + getIsDay()
          + getPrecipIn()
          + getPrecipMm()
          + getPressureIn()
          + getPressureMb()
          + getTempC()
          + getTempF()
          + getTime()
          + getTimeEpoch()
          + getUv()
          + getVisKm()
          + getVisMiles()
          + getWillItRain()
          + getWillItSnow()
          + getWindDegree()
          + getWindDir()
          + getWindKph()
          + getWindMph()
          + getWindchillC()
          + getWindchillF()
          + setAdditionalProperty()
          + setChanceOfRain()
          + setChanceOfSnow()
          + setCloud()
          + setCondition()
          + setDewpointC()
          + setDewpointF()
          + setFeelslikeC()
          + setFeelslikeF()
          + setGustKph()
          + setGustMph()
          + setHeatindexC()
          + setHeatindexF()
          + setHumidity()
          + setIsDay()
          + setPrecipIn()
          + setPrecipMm()
          + setPressureIn()
          + setPressureMb()
          + setTempC()
          + setTempF()
          + setTime()
          + setTimeEpoch()
          + setUv()
          + setVisKm()
          + setVisMiles()
          + setWillItRain()
          + setWillItSnow()
          + setWindDegree()
          + setWindDir()
          + setWindKph()
          + setWindMph()
          + setWindchillC()
          + setWindchillF()
          + toString()
          + withAdditionalProperty()
          + withChanceOfRain()
          + withChanceOfSnow()
          + withCloud()
          + withCondition()
          + withDewpointC()
          + withDewpointF()
          + withFeelslikeC()
          + withFeelslikeF()
          + withGustKph()
          + withGustMph()
          + withHeatindexC()
          + withHeatindexF()
          + withHumidity()
          + withIsDay()
          + withPrecipIn()
          + withPrecipMm()
          + withPressureIn()
          + withPressureMb()
          + withTempC()
          + withTempF()
          + withTime()
          + withTimeEpoch()
          + withUv()
          + withVisKm()
          + withVisMiles()
          + withWillItRain()
          + withWillItSnow()
          + withWindDegree()
          + withWindDir()
          + withWindKph()
          + withWindMph()
          + withWindchillC()
          + withWindchillF()
      }
    }
  }
  

  namespace com.orange {
    namespace models {
      class com.orange.models.Location {
          - additionalProperties : Map<String, Object>
          - country : String
          - lat : double
          - localtime : String
          - localtimeEpoch : int
          - lon : double
          - name : String
          - region : String
          - tzId : String
          + Location()
          + Location()
          + getAdditionalProperties()
          + getCountry()
          + getLat()
          + getLocaltime()
          + getLocaltimeEpoch()
          + getLon()
          + getName()
          + getRegion()
          + getTzId()
          + setAdditionalProperty()
          + setCountry()
          + setLat()
          + setLocaltime()
          + setLocaltimeEpoch()
          + setLon()
          + setName()
          + setRegion()
          + setTzId()
          + toString()
          + withAdditionalProperty()
          + withCountry()
          + withLat()
          + withLocaltime()
          + withLocaltimeEpoch()
          + withLon()
          + withName()
          + withRegion()
          + withTzId()
      }
    }
  }
  

  com.orange.models.Current o-- com.orange.models.Condition : condition
  com.orange.models.Day o-- com.orange.models.Condition__ : condition
  com.orange.models.Forecastday o-- com.orange.models.Astro : astro
  com.orange.models.Forecastday o-- com.orange.models.Day : day
  com.orange.models.Hour o-- com.orange.models.Condition_ : condition


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
